name: Build and test C

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build_and_test_debug:
    name: Build and test
    runs-on: ubuntu-latest
    container: greenbone/pg-gvm-gcc-build:unstable
    steps:
      - uses: actions/checkout@v2

      - name: Build and install extension
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make install
      - name: Start PostgreSQL server
        run: su postgres -c "pg_ctlcluster 13 main start"
      - name: Add "/usr/local/lib" as ld directory
        run: echo "/usr/local/lib" >> /etc/ld.so.conf.d/gvm.conf && ldconfig
      - name: Add pg-gvm extension
        run: psql -d gvmd -c 'SET ROLE dba; CREATE EXTENSION "pg-gvm";'
      - name: Create gvmd tables
        run: psql -d gvmd < gvmd-tables.sql
      - name: Run tests
        run: pg_prove -d gvmd tests/*.sql
