name: Container Image Builds

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: ["v*"]
  workflow_dispatch:


jobs:
  images:
    name: Build and upload container images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Find reference version
        uses: greenbone/actions/reference-version@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ env.VERSION }}
          file: .docker/main.Dockerfile

  upload-build:
    name: "Upload images for building pg-gvm"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Find reference branch
        uses: greenbone/actions/reference-version@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: echo "Build and push ${{ github.repository }}-${{matrix.compiler}}-build:${{ env.VERSION }}"
      - name: Build and push
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          push: true
          tags: ${{ github.repository }}-${{matrix.compiler}}-build:${{ env.VERSION }}
          file: .docker/build.Dockerfile
          build-args: |
            VERSION=${{ env.VERSION }}
            COMPILER=${{matrix.compiler}}
